### PR TITLE
do not rely on annotations to use attributes

### LINKED ISSUE #1344: Broken metadata when updated Doctrine to 2.8.0
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  |  2.0.1
| Symfony version | 6.2.2
| PHP version     | 8.2.0

#### Summary

`Vich\UploaderBundle\Exception\NotUploadableException` on all entities after update Doctrine to 2.8.0

#### Current behavior

All the uploadable entities are broken with `Vich\UploaderBundle\Exception\NotUploadableException`

doctrine/doctrine-bundle doesn't require `doctrine/annotations` anymore which breaks metadata reader, to fix it I've added `doctrine/annotations:1.14.1` to dependencies list, but it seems not to be a correct solution. It'd be nice if we can drop requirement of deprecated library.

#### How to reproduce

composer require doctrine/doctrine-bundle:2.8.0 and refer to any uploadable field of any uploadable entity.

#### Expected behavior

uploadable entities works.

### PR DESCRIPTION
**Pull request by garak**
Fix #1344

### CODE REVIEW

File: src/DependencyInjection/VichUploaderExtension.php [hunk 1]
```diff
@@ -4,13 +4,15 @@
 
 use Doctrine\Common\Annotations\AnnotationReader;
 use Symfony\Component\Config\FileLocator;
+use Symfony\Component\CssSelector\Parser\Reader;
```
Comment (andyexeter) [inline src/DependencyInjection/VichUploaderExtension.php:7]: Wrong class imported here. Should be `Doctrine\Common\Annotations\Reader`.

File: composer.json [hunk 2]
```diff
@@ -58,7 +59,7 @@
         "symfony/yaml": "^5.4 || ^6.0"
     },
     "suggest": {
-        "doctrine/annotations": "If your project use doctrine-bundle:>=2.8, this package is required to use annotations or attributes",
+        "doctrine/annotations": "If you use doctrine/doctrine-bundle >2.7, this package is required to use annotations",
```
Comment (andyexeter) [inline composer.json:62]: Incorrect wording here - the package is required to use annotations _and_ attributes - not just annotations.

File: src/DependencyInjection/VichUploaderExtension.php [hunk 3]
```diff
@@ -138,16 +140,22 @@ protected function registerAnnotationStrategy(ContainerBuilder $container, array
         }
 
         switch ($config['metadata']['type']) {
-            case 'attribute':
+            case 'annotation':
```
Comment (andyexeter) [inline src/DependencyInjection/VichUploaderExtension.php:143]: This does not resolve the issue because this bundle's attribute reader requires `Doctrine\Common\Annotations\Reader` which is part of `doctrine/annotations`.

With this PR, when using attributes the following error is now thrown in src/Metadata/Driver/AttributeReader.php (line 15):

Attempted to load interface "Reader" from namespace "Doctrine\Common\Annotations".
Did you forget a "use" statement for "Symfony\Component\CssSelector\Parser\Reader"?


Screenshot from 2023-02-06 12-35-20

File: composer.json (hunk 2 above)
Comment (garak) [reply composer.json:62]: the purpose of this PR is indeed allowing the use of attributes without relying on doctrine annotations

File: src/DependencyInjection/VichUploaderExtension.php (hunk 1 above)
Comment (garak) [reply src/DependencyInjection/VichUploaderExtension.php]: My bad, fixed

File: src/DependencyInjection/VichUploaderExtension.php (hunk 3 above)
Comment (garak) [reply src/DependencyInjection/VichUploaderExtension.php:142]: It should be working now

Comment (garak) [reply src/DependencyInjection/VichUploaderExtension.php:142]: > This seems to be working for attributes +1

thank you for checking. Do you have the possibility to check it for annotations too? It would be awesome
