### PR TITLE
fix translations

### LINKED ISSUE #1137: vich_file_label create missing translations
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.14.0 
| Symfony version | 4.4.9
| PHP version     | 7.4

#### Summary

Hi @garak, thanks for this useful bundle.

The way VichUploader translate the form label seems buggy to me and report missing translations.
```
{%- block vich_file_label -%}
    {%- set label = label|trans|default(label) -%}
    {{- block('form_label') -}}
{%- endblock -%}
```

Firstly, when using `'label' => false`, it use `trans` on `false` and report a missing translation for `''`. Same when providing no label, it use `trans` on `null`. This leads to an error with Symfony 5. (Cf https://github.com/dustin10/VichUploaderBundle/issues/1066)

Secondly, when using `'label' => 'myLabel'`, it use obviously `trans` on `myLabel`. But the block `form_label` try to translate the label too with the option `'translation_domain'`. This means that the profiler report a missing translation when trying the second translation.

Finally, when using  `'translation_domain' => false`, the label is still translated.

### Solutions

The difficulty would be to determine what is BC and what is BC-break

Currently, If I have the following translations
```
#messages.yaml
myLabel: foo
myLabel2: bar

#VichUploaderBundle.yaml 
myLabel3: baz
bar: hello
```

- `myLabel` will be translated to `foo` with the first trans. (and then foo will be a missing translation in VichUploaderBundle)
- `myLabel2` will be translated to `bar` with the first trans. And then it will be translated to `hello` by `form_label`.
- `myLabel3` will be reported as a missing translation and then will be translated to `baz`.

IMHO the best solution would be to
- add a `delete_translation_domain` option and use it instead of `translation_domain` for `delete_label`.
- add a `download_translation_domain` option and use it instead of `translation_domain` for `download_label`
- change the default value of `translation_domain` to `messages`.
- remove the `{%- set label = label|trans|default(label) -%}` code.
But this would need to release a new major version.

I didn't find a BC way to fix both the fact that `false/null` throw an error with Symfony 5 and the double translate calls which leads to missing translations.

### PR DESCRIPTION
**Pull request by garak**
Fix #1137

### CODE REVIEW

File: src/Form/Type/VichFileType.php [hunk 1]
```diff
@@ -65,11 +65,10 @@ public function configureOptions(OptionsResolver $resolver): void
...
             'download_link' => null,
             'download_uri' => true,
-            //TODO: use 'form.label.download'
-            'download_label' => 'download',
-            'delete_label' => 'form.label.delete',
+            'download_label' => 'vich_uploader.link.download',
+            'delete_label' => 'vich_uploader.form_label.delete_confirm',
             'error_bubbling' => false,
-            'translation_domain' => 'VichUploaderBundle',
+            'translation_domain' => 'messages',
```
Comment (VincentLanglet) [inline src/Form/Type/VichFileType.php:71]: It's already the default value, I don't think you need this line.

**Comment by VincentLanglet** [comment]
Hi @garak ! 
Do you plan to make a new release with this ? It'll avoid to require a specific commit or dev-master. :)

**Comment by garak** [comment]
Yes, new version will be released between today and tomorrow
